### ISSUE TITLE
contador de metros nadados

### ISSUE THREAD

**Issue by euharrison** [euharrison/coliformia-games#16]

**Comment by euharrison** [comment]
@RMontSerrat te adicionei nessa tarefa, foi isso q comentou no facebook confere?

**Comment by RMontSerrat** [comment]
isso, xá comigo

**Comment by euharrison** [comment]
@RMontSerrat o @Vamoss deu um gás em alguns itens iniciais e um deles é um score, depois dá uma olhada e veja se tem como relacionar o que ele fez com o que está projetando https://github.com/euharrison/coliformia-games/commit/9537c61e8ec9fb6faca49ab06053585b8dd67770
