### ISSUE TITLE
power down

### ISSUE THREAD

**Issue by euharrison** [euharrison/coliformia-games#17]
bater em power down retira 50 pontos de life, este valor pode variar por diversos motivos, mas para um MVP vamos deixar ele fixo e depois deixamos ele dinamico

**Comment by euharrison** [comment]
closed by commit ???? 
:sunglasses:

**Comment by amarocolas** [comment]
isso não está rolando.... você morre se bater nos powerdown :)

**Comment by euharrison** [comment]
ih, surtei hahah
