### ISSUE TITLE
game.scale.setScreenSize is not a function

### ISSUE THREAD

**Issue by euharrison** [euharrison/coliformia-games#2]
@amarocolas pode ajudar neste?

![screen shot 2015-09-22 at 8 28 06 pm](https://cloud.githubusercontent.com/assets/557598/10034616/81ea59c0-6168-11e5-9722-ec011d5f453b.png)

**Comment by amarocolas** [comment]
o phaser usa uma API que foi deprecada, achei esse thread aqui falando disso.

http://gamedev.stackexchange.com/questions/105043/typeerror-this-scale-setscreensize-is-not-a-function

de qualquer forma, removi um monte de coisa de escala e o erro sumiu
